// @ts-expect-error - generated by wasm-pack at build time
import init, { run_vrl } from "./pkg/vrl_runner";

let ready: Promise<void> | null = null;
export function ensureWasm(): Promise<void> {
  return (ready ??= init().then(() => undefined));
}

export type VrlOk = {
  target_value: unknown;
  runtime_result: unknown;
  elapsed_time: number | null;
};
export type VrlErr = {
  list: string[];
  msg: string;
  msg_colorized: string;
};
export type VrlResult = VrlOk | VrlErr;

export async function runVrl(
  program: string,
  event: unknown,
  tz = "UTC"
): Promise<VrlResult> {
  await ensureWasm();
  return run_vrl({ program, event }, tz) as VrlResult;
}

export function isErr(r: VrlResult): r is VrlErr {
  return typeof (r as VrlErr).msg === "string";
}
